create database DSEC;
use DSEC;
create table customers(age int,id int,customername varchar(30),address varchar(30),city varchar(30));
select id,customername from customers;
select * from customers where city='chennai';
select * from customers where id=1;
insert into customers values(19,1,'rahul','tambaram','chennai'); 
insert into customers values(19,2,'rahii','gandhipuram','kovai'); 
insert into customers values(20,3,'ariharalingam','devakottai','karaikudi'); 
insert into customers values(21,1,'varsha','esanoor','nagapattinam'); 
select * from customers;
select * from customers where age>=20;
select * from customers where age BETWEEN 19  AND 21;
select * from customers where customername like 'r%';
select * from customers where customername like '%ah%';
select * from customers where city in ('kovai','gandhipuram');
insert into customers values(20,0,'hul','trichy','chennai'); 
insert into customers values(19,0,'mahi','puram','chennai'); 
insert into customers values(23,3,'ariharalingam','devakottai','karaikudi'); 
insert into customers values(21,1,'varsha','devakottai','karaikudi');
select * from customers where city='nagapattinam' or city='karaikudi';
select * from customers where not city='chennai';
select * from customers order by id;
select * from customers order by id desc;
drop database dsec;